name: Cooldowns
main: com.github.neapovil.cooldowns.Cooldowns
version: 1.0.0
api-version: 1.19
author: Neapovil
website: https://github.com/Neapovil/cooldowns
depend:
  - CommandAPI
permissions:
  cooldowns.command:
    default: op
